'use strict';

const router = require('express').Router();
const path = require('path');
const fs = require('fs');
const { makeJobId } = require('../services/sse');
const { webhookLimiter } = require('../middleware/rate-limit');
const { apiKeyAuth } = require('../middleware/auth');
const { redactEmail } = require('../utils/redact');
const db = require('../src/node/db');
const { sendMail } = require('../services/email');

// GET /demos - Gallery page
router.get('/demos', async (req, res) => {
    const demosDir = path.join(__dirname, '..', 'public', 'demos');
    try {
        const entries = await fs.promises.readdir(demosDir, { withFileTypes: true });
        const demos = entries.filter(e => e.isDirectory()).map(e => e.name);
        const html = `
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Demo Sites</title>
                <style>
                    body { font-family: sans-serif; background-color: #111; color: #eee; padding: 2rem; }
                    h1 { margin-bottom: 2rem; color: #fff; }
                    ul { list-style: none; padding: 0; }
                    li { margin-bottom: 1rem; }
                    a { color: #8b5cf6; text-decoration: none; font-size: 1.1rem; }
                    a:hover { text-decoration: underline; }
                </style>
            </head>
            <body>
                <h1>Generated Demo Sites (${demos.length})</h1>
                <ul>
                    ${demos.map(demo => `<li><a href="/demos/${demo}/index.html" target="_blank">${demo}</a></li>`).join('')}
                </ul>
            </body>
            </html>
        `;
        res.send(html);
    } catch (err) {
        res.status(500).send(`<h1>Error</h1><p>Could not read demos directory.</p><p>${err.message}</p><p>Did you run the generator script first?</p>`);
    }
});

const PORT = process.env.PORT || 3000;
const templateSubmissions = []; // in-memory store for /api/template-submissions

// GET /demo — personalized demo preview via query params
router.get('/demo', async (req, res) => {
    const templatePath = path.join(__dirname, '..', 'template.html');
    try { await fs.promises.access(templatePath); } catch {
        return res.status(404).send('Demo template not found.');
    }

    const business = {
        name: (req.query.name || req.query.shop || 'Your Smoke Shop').slice(0, 200),
        city: (req.query.city || 'Your City').slice(0, 100),
        state: (req.query.state || 'TX').slice(0, 10),
        phone: (req.query.phone || '(000) 000-0000').slice(0, 20),
        address: (req.query.address || '').slice(0, 200),
        rating: (req.query.rating || '4.5').slice(0, 5),
        reviews: (req.query.reviews || '50+').slice(0, 10),
        hours: (req.query.hours || 'Mon–Sun 9am–10pm').slice(0, 100),
    };

    let html = await fs.promises.readFile(templatePath, 'utf8');

    const nameParts = business.name.split(' ');
    const mid = Math.ceil(nameParts.length / 2);
    const line1 = nameParts.slice(0, mid).join(' ');
    const line2 = nameParts.slice(mid).join(' ');
    const phoneClean = business.phone.replace(/\D/g, '');
    const ratingNum = parseFloat(business.rating) || 4.5;
    const stars = '★'.repeat(Math.round(ratingNum)) + '☆'.repeat(5 - Math.round(ratingNum));
    const slug = business.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50);
    const addrEncoded = encodeURIComponent(`${business.name}, ${business.address || business.city}, ${business.state}`);

    html = html.replace(/{{BUSINESS_NAME}}/g, business.name);
    html = html.replace(/{{BUSINESS_LINE1}}/g, line1);
    html = html.replace(/{{BUSINESS_LINE2}}/g, line2);
    html = html.replace(/{{CITY}}/g, business.city);
    html = html.replace(/{{STATE}}/g, business.state);
    html = html.replace(/{{ADDRESS}}/g, business.address || `${business.city}, ${business.state}`);
    html = html.replace(/{{PHONE}}/g, business.phone);
    html = html.replace(/{{PHONE_CLEAN}}/g, phoneClean);
    html = html.replace(/{{RATING}}/g, business.rating);
    html = html.replace(/{{STARS}}/g, stars);
    html = html.replace(/{{REVIEWS}}/g, business.reviews);
    html = html.replace(/{{HOURS}}/g, business.hours);
    html = html.replace(/{{MAP_EMBED}}/g, `https://www.google.com/maps?q=${addrEncoded}&output=embed`);
    html = html.replace(/{{SLUG}}/g, slug);
    html = html.replace(/{{CONTACT_PHONE}}/g, process.env.CONTACT_PHONE || '2813230450');
    html = html.replace(/{{CONTACT_PHONE_FORMATTED}}/g, '(281) 323-0450');

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.send(html);
});

// GET /demo/:slug — serve pre-generated demo sites
router.get('/demo/:slug', (req, res) => {
    const slug = req.params.slug.replace(/[^a-z0-9-]/g, '');
    
    // Check data/demos/ first (generated by generate_site.js)
    const dataPath = path.join(__dirname, '..', 'data', 'demos', `${slug}.html`);
    if (fs.existsSync(dataPath)) return res.sendFile(dataPath);

    // Check public/demos/ directories
    const pubPath = path.join(__dirname, '..', 'public', 'demos', slug, 'index.html');
    if (fs.existsSync(pubPath)) return res.sendFile(pubPath);

    res.status(404).send('<h1>Demo not found</h1><p>This demo may not have been generated yet.</p>');
});

// POST /api/send-demo
router.post('/api/send-demo', webhookLimiter, async (req, res) => {
    const { email, business_name, city = '', phone = '', instagram = '', place_id = '' } = req.body || {};
    if (!email || !business_name) return res.status(400).json({ error: 'email and business_name required' });

    const fromName = process.env.FROM_NAME || 'Alex';
    const serverBase = process.env.DEMO_BASE_URL || `http://localhost:${PORT}`;
    
    // We will still support the dynamic demoUrl, but if we want to "scaffold" we will build a URL
    let demoUrl = `${serverBase}/demo?name=${encodeURIComponent(business_name)}&city=${encodeURIComponent(city)}&phone=${encodeURIComponent(phone)}`;

    // Optional Static Scaffold Phase
    if (place_id) {
        try {
            // Very simple inline scaffolding placeholder to fulfill master prompt '.scaffoldDeployment'
            const slug = business_name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50);
            const scaffoldUrl = `${serverBase}/demos/${slug}/index.html`;
            demoUrl = scaffoldUrl;

            // Trigger actual generation if needed (assumes generate-from-templates will be run or hit)
            // For MVP, we save the slug URL to CRM.
            db.db.prepare("UPDATE leads SET demo_url = ?, crm_stage = 'demo_sent' WHERE place_id = ?").run(demoUrl, place_id);
            db.logInteraction.run(place_id, 'email', `Sent Auto Demo: ${demoUrl}`);
        } catch (err) {
            console.error('Failed to scaffold demo:', err);
        }
    }

    try {
        const sent = await sendMail({
            from: `"${fromName}" <${process.env.SMTP_USER}>`,
            to: email,
            subject: `Your custom website demo for ${business_name}`,
            html: `<div style="font-family:sans-serif;max-width:580px;margin:0 auto;padding:40px 24px;background:#0a0a0a;color:#fff;">
                <h1 style="color:#dc2626;">Here's your custom demo, ${business_name}!</h1>
                <p style="color:#ccc;line-height:1.7;">We put together a premium website just for <strong>${business_name}</strong>. Click below to check it out:</p>
                <div style="text-align:center;margin:32px 0;">
                    <a href="${demoUrl}" style="display:inline-block;background:linear-gradient(135deg,#dc2626,#b91c1c);color:#fff;font-weight:700;padding:14px 36px;border-radius:8px;font-size:1.1rem;text-decoration:none;">View Your Custom Website</a>
                </div>
                <p style="color:#aaa;font-size:.9rem;line-height:1.7;">This is a custom design for your shop — only $200 to make it yours. Questions? Call us at (281) 323-0450 or visit smokeshopgrowth.com</p>
                <hr style="border:none;border-top:1px solid #222;margin:32px 0;"/>
                <p style="color:#666;font-size:.82rem;">${fromName} • SmokeShopGrowth</p>
            </div>`,
        });
        if (!sent) return res.status(503).json({ error: 'Email service not configured' });

        res.json({ success: true, demoUrl });
    } catch (err) {
        console.error('Demo email error:', err.message);
        res.status(500).json({ error: err.message });
    }
});

// POST /api/submit-lead
router.post('/api/submit-lead', webhookLimiter, async (req, res) => {
    const { contactName, email, phone, tier, businessName, city } = req.body || {};
    if (!email || !contactName) return res.status(400).json({ error: 'Name and email required' });

    const submissionDate = new Date().toISOString();
    try {
        const dataDir = path.join(__dirname, '..', 'data');
        if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir);
        const csvPath = path.join(dataDir, 'submissions.csv');
        if (!fs.existsSync(csvPath)) fs.writeFileSync(csvPath, "Date,Contact Name,Email,Phone,Tier,Business,City\n");
        fs.appendFileSync(csvPath, `"${submissionDate}","${contactName}","${email}","${phone}","${tier}","${businessName}","${city}"\n`);
        console.log(`Lead captured: ${redactEmail(email)} for ${businessName}`);
        res.json({ success: true, message: 'Lead captured!' });
    } catch (err) {
        console.error('Lead capture error:', err.message);
        res.status(500).json({ error: 'Failed to save lead' });
    }
});

// POST /api/template-submission
router.post('/api/template-submission', webhookLimiter, async (req, res) => {
    try {
        const { shopName, city, phone, email } = req.body;
        if (!shopName || !city || !phone || !email) return res.status(400).json({ error: 'Missing required fields' });

        const submission = { id: makeJobId(), shopName: String(shopName).trim(), city: String(city).trim(), phone: String(phone).trim(), email: String(email).trim(), timestamp: new Date().toISOString() };
        templateSubmissions.push(submission);

        const dataDir = path.join(__dirname, '..', 'data');
        if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir);
        const csvPath = path.join(dataDir, 'submissions.csv');
        if (!fs.existsSync(csvPath)) fs.writeFileSync(csvPath, 'id,timestamp,shopName,city,phone,email\n');
        fs.appendFileSync(csvPath, `"${submission.id}","${submission.timestamp}","${submission.shopName}","${submission.city}","${submission.phone}","${submission.email}"\n`);

        res.json({ success: true, message: "Thank you! We'll contact you shortly.", submissionId: submission.id });
    } catch (err) {
        console.error('Form error:', err.message);
        res.status(500).json({ error: 'Failed to process' });
    }
});

router.get('/api/template-submissions', apiKeyAuth, (req, res) => res.json({ count: templateSubmissions.length, submissions: templateSubmissions }));

module.exports = router;
